server {
    listen 443 ssl http2;

    ssl_certificate /etc/nginx/certificates/tls-cert.pem;
    ssl_certificate_key /etc/nginx/certificates/tls-key.pem;

    # o11y
    location /nginx_status {
        stub_status on;
        access_log off;
    }

    location /assets/ {
            root /home/isucon/webapp/public/;
            try_files $uri http://127.0.0.1:3000;
            expires 1d;
    }

    location /api/trend {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000;

        proxy_cache trend_cache;
        proxy_cache_valid 200 3s; # TODO: 調整
    }

    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://127.0.0.1:3000;
    }
}

proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=trend_cache:10m max_size=1g inactive=3m use_temp_path=off;
proxy_cache_key "$scheme$request_method$host$request_uri";
